project_name: bp

builds:
  - id: bp
    main: ./bp/main.go
    binary: bp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ukhirani/boilerplate/constants.VERSION={{ .Version }}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: bp
    homepage: https://github.com/ukhirani/boilerplate
    description: Skip writing repetitive boilerplate code
    license: MIT

    repository:
      owner: ukhirani
      name: homebrew-bp

    folder: Formula

    install: |
      bin.install "bp"

winget:
  - name: bp
    publisher: ukhirani
    publisher_url: https://github.com/ukhirani
    publisher_support_url: https://github.com/ukhirani/boilerplate/issues
    package_identifier: Ukhirani.Bp
    homepage: https://github.com/ukhirani/boilerplate
    short_description: Skip writing repetitive boilerplate code
    license: MIT
    license_url: https://github.com/ukhirani/boilerplate/blob/main/LICENSE
    repository:
      owner: ukhirani
      name: winget-pkgs
      branch: master
